# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rhythm of rein
email: reinhardt.cgr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal cove to recover, contemplate, or share - Welcome to all
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reinhardtcgr.github.io/" # the base hostname & protocol for your site
twitter_username: rhythmofrein
github_username:  reinhardtcgr
linkedin_username:  reinhardtcagara
salutations: "Go out & play!"

# Build settings
markdown: kramdown
