# Dependencies

#// redcarpet not supported on Jekyll 4+
markdown:         kramdown
highlighter:      pygments

paginate:         3
paginate_path: "/logs/:num"

# Permalinks
#permalink:        pretty
permalink:        /:year/:month/:day/:title/

# Setup
title:            Reinhardt
tagline:          'We endeavor'

#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description: > # this means to ignore newlines until "baseurl:"
  Gateway to another space. Breadcrumbs to a life lived.

#// the base hostname & protocol for your site
url: "https://reinhardt021.github.io" 
#// works local site.url>>.baseurl + / added to broken
baseurl: '' 

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


# Custom vars
version:          2.1.0
twitter:          https://twitter.com/reinhardt021
mygithub:           https://github.com/reinhardt021
linkedin:         https://linkedin.com/in/reinhardtcagara

github:
  repo:           https://github.com/reinhardt021/reinhardt021.github.io

kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
