# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rhythm of Rein
email: reinhardt.cgr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curated Collection of Personal Projects and Obscure Opinions.
  Rhythm of Rein is the nexus of my nootropic nonsense.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reinhardtcgr.github.io/" # the base hostname & protocol for your site
twitter_username: thefreshaer
github_username:  reinhardtcgr
linkedin_username:  reinhardtcagara
salutations: ".: learn love live - autumn :."

# Build settings
markdown: kramdown
