# Dependencies
markdown:         kramdown #// redcarpet not supported on Jekyll 4+
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Reinhardt
tagline:          'We endeavor'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description: > # this means to ignore newlines until "baseurl:"
  Gateway to another reality. Breadcrumbs to a life lived.
url: "http://reinhardt021.github.io/" # the base hostname & protocol for your site
baseurl: / # `/` needed for relative permalinks; else About page won't load


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0
twitter:          https://twitter.com/reinhardt021
mygithub:           https://github.com/reinhardt021
linkedin:         https://linkedin.com/in/reinhardtcagara

#github:
  #repo:           https://github.com/poole/hyde
#github: [metadata]
github:
  repo:           https://github.com/reinhardt021/reinhardt021.github.io
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
